
== AWS Vault

> AWS Vault is a tool to securely store and access AWS credentials in a development environment.

> AWS Vault stores IAM credentials in your operating system's secure keystore and then generates temporary credentials from those to expose to your shell and applications. It's designed to be complementary to the AWS CLI tools, and is aware of your profiles and configuration in ~/.aws/config.
-- https://github.com/99designs/aws-vault

NOTE: インストールについては
https://github.com/99designs/aws-vault#installing[99designs/aws-vault#installing]
を参照

----
$ aws-vault --version
v6.0.0-beta5
----

=== AWS Vaultの主な機能

- **AWS CLIの補完ツール**であるということ
- OSのセキュアなkeystoreに保存(MacOSならkeychain)
- 一時認証情報を用いて**環境変数として**展開
- RoleなしのMFAでも対応

=== AWS Vaultの設定
https://github.com/99designs/aws-vault/blob/master/USAGE.md#managing-credentials


==== Credentialの追加
TIP: 自分のアクセスキーを使用して設定

NOTE: SSO Userはこの手順は不要

----
$ aws-vault add produser
Enter Access Key Id: ABDCDEFDASDASF
Enter Secret Key: %
----

NOTE: ~/.aws/.credentialは使われない

==== AWS CLI 設定

TIP: 自分にあった設定を行う

===== IAM User かつ MFA serialだけを使用した設定

----
[profile produser]
output=json
region=ap-northeast-1
mfa_serial = arn:aws:iam::123456789012:mfa/produser
----

===== IAM User かつ IAM RoleとMFA serialを使用した設定

----
[profile produser]
output=json
region=ap-northeast-1

[profile poweruser]
mfa_serial = arn:aws:iam::123456789012:mfa/produser
role_arn = arn:aws:iam::123456789012:role/power-access
source_profile = produser
----

===== SSO Userの設定

----
[profile sso-produser]
sso_start_url = https://awssso.awsapps.com/start
sso_region = us-east-1
sso_account_id = 1234567890
sso_role_name = AWSAdministratorAccess

----

NOTE: 自分のアカウント設定を確認

=== AWS Vaultの使用

TIP: 実行してみる

==== Profile一覧

----
$ aws-vault list
Profile                  Credentials              Sessions
=======                  ===========              ========
default                  -                        -
produser                 -                        -
----

==== コマンド実行

----
$ aws-vault exec produser -- aws sts get-caller-identity
{
    "UserId": "AIDASAMPLEUSERID",
    "Account": "1234567890123",
    "Arn": "arn:aws:iam::1234567890123:user/produser"
}
----


----
$ aws-vault exec produser -- env | grep AWS
AWS_ACCESS_KEY_ID=xxx
AWS_DEFAULT_REGION=ap-northeast-1
AWS_REGION=ap-northeast-1
AWS_SECRET_ACCESS_KEY=xxx
AWS_SECURITY_TOKEN=xxx
AWS_SESSION_EXPIRATION=2020-08-14T13:03:20Z
AWS_SESSION_TOKEN=xxx
----

----
$ aws-vault exec produser -- aws s3 ls
2013-07-11 17:08:50 mybucket
2013-07-24 14:55:44 mybucket2
----

----
$ aws-vault exec produser -- $SHELL
$ env | grep AWS
AWS_ACCESS_KEY_ID=xxx
AWS_DEFAULT_REGION=ap-northeast-1
AWS_REGION=ap-northeast-1
AWS_SECRET_ACCESS_KEY=xxx
AWS_SECURITY_TOKEN=xxx
AWS_SESSION_EXPIRATION=2020-08-14T13:03:20Z
AWS_SESSION_TOKEN=xxx
$ aws sts get-caller-identity
{
    "UserId": "AIDASAMPLEUSERID",
    "Account": "1234567890123",
    "Arn": "arn:aws:iam::1234567890123:user/produser"
}
$ aws s3 ls
2013-07-11 17:08:50 mybucket
2013-07-24 14:55:44 mybucket2
$ exit
----

----
$ aws-vault list
Profile                  Credentials              Sessions
=======                  ===========              ========
default                  -                        -
produser                 produser                 sts.GetSessionToken:4h17m13s
----
